### ISSUE TITLE
Only GeoJSON FeatureCollection?

### ISSUE THREAD

**Issue by lzumbach** [andreacremaschi/GEOSwift#1] opened 2015-06-19 22:32 UTC
It looks like the GeoJSON parsing only works if you have a FeatureCollection?  The GeoJSON I use does not use that.  It has a type of Feature.  I can send you some samples if that helps.

Thanks!

**Comment by andreacremaschi** [comment] 2015-06-20 16:08
Ouch you're right, as it seems I misunderstood that part of the specification.. I'll correct that as soon as possible. Thank you

**Comment by andreacremaschi** [comment] 2015-06-23 12:29
Hey @lzumbach this issue should be fixed, can you confirm that everything is working for you?
You should redirect your `Podfile` to use the last commit in `develop`, like this:

```
pod 'GEOSwift', :branch => 'develop'
```

**Comment by lzumbach** [comment] 2015-06-23 13:56
I think it is working but I think I am doing something wrong when I try to convert to a MapKit overlay:
                if let fieldgeom = Geometry.fromGeoJSON(url!) {
                    let fieldgeom = fieldgeom[0] as? MultiPolygon
                    let shape = fieldgeom?.mapShape() as? MKPolygon
                    mapView.addOverlay(shape)
                }
Not sure I understand how mapShape() works.  I don't suppose I can expect to cast an MultiPolygon to an MKPolygon?  shape ends up nil.  Do I need a custom overlay and overlay renderer?

**Comment by lzumbach** [comment] 2015-06-23 14:17
{"id":null,"geometry":{"coordinates":[[[
  [
    -91.638232603671142,
    42.149637959173383
  ],
  [
    -91.638232554764926,
    42.14963796031703
  ],
  [
    -91.638232505973164,
    42.149637963851063
  ],
  [
    -91.638232457412627,
    42.149637969767021
  ],
  [
    -91.6382324091995,
    42.149637978050755
  ],
  [
    -91.638232361449184,
    42.149637988682436
  ],
  [
    -91.638232314275953,
    42.149638001636625
  ],
  [
    -91.638232267792688,
    42.149638016882314
  ],
  [
    -91.638232222110616,
    42.149638034383024
  ],
  [
    -91.638232177339091,
    42.149638054096876
  ],
  [
    -91.638232133585248,
    42.149638075976682
  ],
  [
    -91.638232090953778,
    42.14963809997009
  ],
  [
    -91.63823204954673,
    42.149638126019674
  ],
  [
    -91.638232009463167,
    42.1496381540631
  ],
  [
    -91.63823197079904,
    42.149638184033257
  ],
  [
    -91.638231933646864,
    42.149638215858417
  ],
  [
    -91.63823189809554,
    42.14963824946242
  ],
  [
    -91.638231864230164,
    42.149638284764855
  ],
  [
    -91.63823183213178,
    42.149638321681223
  ],
  [
    -91.638231801877183,
    42.1496383601232
  ],
  [
    -91.6382317735388,
    42.149638399998764
  ],
  [
    -91.638231747184435,
    42.14963844121251
  ],
  [
    -91.638231722877165,
    42.149638483665804
  ],
  [
    -91.638231700675149,
    42.149638527257039
  ],
  [
    -91.638231680631534,
    42.1496385718819
  ],
  [
    -91.638231662794269,
    42.1496386174336
  ],
  [
    -91.638231647206055,
    42.149638663803131
  ],
  [
    -91.6382316339042,
    42.149638710879515
  ],
  [
    -91.638231622920514,
    42.14963875855009
  ],
  [
    -91.63823161428131,
    42.149638806700786
  ],
  [
    -91.638231608007246,
    42.149638855216367
  ],
  [
    -91.638231604113344,
    42.14963890398073
  ],
  [
    -91.638231602608911,
    42.149638952877169
  ],
  [
    -91.63823102134441,
    42.149731279310743
  ],
  [
    -91.63823102134441,
    42.149731279310743
  ],
  [
    -91.638228118985509,
    42.150192279803917
  ],
  [
    -91.638228118985509,
    42.150192279803917
  ],
  [
    -91.638227204435708,
    42.150337542991316
  ],
  [
    -91.638227204435708,
    42.150337542991352
  ],
  [
    -91.638227204435708,
    42.150337542991352
  ],
  [
    -91.638225049306016,
    42.150679856539128
  ],
  [
    -91.638225049306016,
    42.150679856539128
  ],
  [
    -91.638224779624707,
    42.150722691676421
  ],
  [
    -91.638224779624707,
    42.150722691676421
  ],
  [
    -91.63822402860761,
    42.150841980171521
  ],
  [
    -91.63822402860761,
    42.150841980171542
  ],
  [
    -91.63822402860761,
    42.150841980171542
  ],
  [
    -91.638220153147913,
    42.151457544350542
  ],
  [
    -91.638220153147913,
    42.151457544350549
  ],
  [
    -91.638220153147913,
    42.151457544350549
  ],
  [
    -91.638217759743114,
    42.151837704708818
  ],
  [
    -91.638217759743114,
    42.151837704708818
  ],
  [
    -91.638216738232458,
    42.151999957307666
  ],
  [
    -91.638211506224053,
    42.152167513286372
  ],
  [
    -91.638211506224053,
    42.152167513286493
  ],
  [
    -91.638209492191748,
    42.152232013206266
  ],
  [
    -91.638209492191748,
    42.152232013206707
  ],
  [
    -91.638198084514471,
    42.152597345865956
  ],
  [
    -91.638198084027763,
    42.152597376121307
  ],
  [
    -91.638197453299568,
    42.153257898279193
  ],
  [
    -91.6381961994496,
    42.15329030645448
  ],
  [
    -91.6381961994496,
    42.15329030645448
  ],
  [
    -91.6381939854867,
    42.153347530561035
  ],
  [
    -91.6381939854867,
    42.153347530561035
  ],
  [
    -91.6381900361307,
    42.15344960909573
  ],
  [
    -91.6381900361307,
    42.153449609095873
  ],
  [
    -91.6381754202709,
    42.15382738434635
  ],
  [
    -91.6381754202709,
    42.15382738434635
  ],
  [
    -91.63816774707459,
    42.154025712080745
  ],
  [
    -91.63816774707459,
    42.154025712080923
  ],
  [
    -91.6380939502793,
    42.15593313041456
  ],
  [
    -91.638093949889736,
    42.155933142318119
  ],
  [
    -91.638093683511826,
    42.155943094247121
  ],
  [
    -91.638093683511826,
    42.155943094247291
  ],
  [
    -91.638091351653628,
    42.156030213415541
  ],
  [
    -91.638091351653628,
    42.156030213415541
  ],
  [
    -91.638089127090936,
    42.156113323867991
  ],
  [
    -91.638089127090936,
    42.156113323867991
  ],
  [
    -91.638085163573933,
    42.156261402000744
  ],
  [
    -91.638085163573933,
    42.156261402000744
  ],
  [
    -91.638082868159728,
    42.15634715917836
  ],
  [
    -91.638082868159728,
    42.15634715917836
  ],
  [
    -91.638073966918427,
    42.156679710381063
  ],
  [
    -91.638073966918427,
    42.156679710381063
  ],
  [
    -91.638071301969731,
    42.156779272768965
  ],
  [
    -91.638071301877446,
    42.156779322578942
  ],
  [
    -91.638071304265551,
    42.156779372331727
  ],
  [
    -91.638071309128122,
    42.156779421903877
  ],
  [
    -91.638071316453079,
    42.1567794711724
  ],
  [
    -91.638071326222246,
    42.156779520015064
  ],
  [
    -91.638071338411407,
    42.156779568310682
  ],
  [
    -91.638071352990309,
    42.156779615939442
  ],
  [
    -91.638071369922784,
    42.156779662783158
  ],
  [
    -91.638071389166811,
    42.156779708725622
  ],
  [
    -91.638071410674655,
    42.156779753652842
  ],
  [
    -91.638071434392955,
    42.156779797453353
  ],
  [
    -91.63807146026285,
    42.156779840018487
  ],
  [
    -91.638071488220177,
    42.156779881242635
  ],
  [
    -91.638071518195574,
    42.156779921023521
  ],
  [
    -91.638071550114645,
    42.156779959262444
  ],
  [
    -91.63807158389821,
    42.156779995864532
  ],
  [
    -91.638071619462465,
    42.156780030738979
  ],
  [
    -91.638071656719148,
    42.156780063799253
  ],
  [
    -91.638071695575846,
    42.156780094963331
  ],
  [
    -91.638071735936137,
    42.1567801241539
  ],
  [
    -91.638071777699892,
    42.15678015129852
  ],
  [
    -91.638071820763514,
    42.156780176329868
  ],
  [
    -91.638071865020123,
    42.156780199185825
  ],
  [
    -91.63807191035994,
    42.156780219809683
  ],
  [
    -91.638071956670458,
    42.156780238150283
  ],
  [
    -91.638072003836811,
    42.156780254162115
  ],
  [
    -91.638072051741943,
    42.156780267805452
  ],
  [
    -91.63807210026701,
    42.156780279046451
  ],
  [
    -91.638072149291631,
    42.156780287857217
  ],
  [
    -91.638072198694147,
    42.156780294215892
  ],
  [
    -91.638072248352017,
    42.156780298106696
  ],
  [
    -91.638072298142035,
    42.15678029951998
  ],
  [
    -91.638192778797233,
    42.15678071754958
  ],
  [
    -91.642010085767737,
    42.156793962391077
  ],
  [
    -91.64240057394133,
    42.156795317261079
  ],
  [
    -91.644440656497537,
    42.156802395698776
  ],
  [
    -91.645200274534332,
    42.156805031331878
  ],
  [
    -91.645483445681634,
    42.156806013845681
  ],
  [
    -91.645884197213235,
    42.156807404326081
  ],
  [
    -91.64640409101554,
    42.156809208192279
  ],
  [
    -91.646634258103731,
    42.156810006798878
  ],
  [
    -91.646671273564337,
    42.156810135230778
  ],
  [
    -91.647077252844241,
    42.156811543849777
  ],
  [
    -91.647838600669829,
    42.156814185484578
  ],
  [
    -91.647838651698279,
    42.156814184359035
  ],
  [
    -91.64783870260284,
    42.156814180631279
  ],
  [
    -91.647838753250866,
    42.156814174311009
  ],
  [
    -91.647838803510453,
    42.156814165414687
  ],
  [
    -91.647838853250633,
    42.156814153965506
  ],
  [
    -91.647838902341846,
    42.15681413999328
  ],
  [
    -91.64783895065618,
    42.15681412353441
  ],
  [
    -91.647838998067783,
    42.156814104631778
  ],
  [
    -91.647839044453136,
    42.156814083334623
  ],
  [
    -91.6478390896914,
    42.156814059698441
  ],
  [
    -91.647839133664718,
    42.156814033784791
  ],
  [
    -91.647839176258529,
    42.1568140056612
  ],
  [
    -91.647839217361877,
    42.156813975400915
  ],
  [
    -91.647839256867684,
    42.156813943082788
  ],
  [
    -91.64783929467302,
    42.156813908791
  ],
  [
    -91.647839330679389,
    42.15681387261489
  ],
  [
    -91.647839364793,
    42.156813834648709
  ],
  [
    -91.647839396924979,
    42.156813794991358
  ],
  [
    -91.647839426991624,
    42.156813753746157
  ],
  [
    -91.6478394549146,
    42.156813711020554
  ],
  [
    -91.647839480621158,
    42.156813666925849
  ],
  [
    -91.647839504044342,
    42.15681362157693
  ],
  [
    -91.6478395251231,
    42.156813575091931
  ],
  [
    -91.647839543802561,
    42.156813527591957
  ],
  [
    -91.647839560034029,
    42.15681347920075
  ],
  [
    -91.647839573775229,
    42.156813430044373
  ],
  [
    -91.647839584990365,
    42.156813380250895
  ],
  [
    -91.647839593650218,
    42.156813329950033
  ],
  [
    -91.647839599732237,
    42.156813279272832
  ],
  [
    -91.647839603220561,
    42.156813228351311
  ],
  [
    -91.64783960410611,
    42.156813177318128
  ],
  [
    -91.647839602386568,
    42.15681312630624
  ],
  [
    -91.647837317902571,
    42.156774594513138
  ],
  [
    -91.647837317902557,
    42.156774594512918
  ],
  [
    -91.6478280353515,
    42.156618027915862
  ],
  [
    -91.6478280353515,
    42.156618027915862
  ],
  [
    -91.647820722817684,
    42.156494688858061
  ],
  [
    -91.647820722817642,
    42.15649468885762
  ],
  [
    -91.6478050833252,
    42.156230899827747
  ],
  [
    -91.647805083325181,
    42.156230899827584
  ],
  [
    -91.6478050833252,
    42.156230899827584
  ],
  [
    -91.647794777571988,
    42.15605707466748
  ],
  [
    -91.647794777571974,
    42.156057074667238
  ],
  [
    -91.6477935521106,
    42.156036405012742
  ],
  [
    -91.6477927224497,
    42.155864938290648
  ],
  [
    -91.6477927224497,
    42.155864938290648
  ],
  [
    -91.64779215570799,
    42.155747809027062
  ],
  [
    -91.64779215570799,
    42.155747809027062
  ],
  [
    -91.647790718912688,
    42.155450863651176
  ],
  [
    -91.647790718912688,
    42.155450863651168
  ],
  [
    -91.647788847930784,
    42.1550641819675
  ],
  [
    -91.647788847930784,
    42.155064181967489
  ],
  [
    -91.647788600796588,
    42.155013105778814
  ],
  [
    -91.647788600796588,
    42.155013105778814
  ],
  [
    -91.6477874121829,
    42.154767449822025
  ],
  [
    -91.6477874121829,
    42.154767449821982
  ],
  [
    -91.6477874121829,
    42.154767449821982
  ],
  [
    -91.647786847874187,
    42.154650822810481
  ],
  [
    -91.647786847874187,
    42.154650822810481
  ],
  [
    -91.647785949674187,
    42.154465189254594
  ],
  [
    -91.647785948260122,
    42.154465140712418
  ],
  [
    -91.647785944491091,
    42.154465092296135
  ],
  [
    -91.647785938375961,
    42.154465044119917
  ],
  [
    -91.647785929929157,
    42.154464996297392
  ],
  [
    -91.647785919170616,
    42.154464948941339
  ],
  [
    -91.647785906125691,
    42.154464902163433
  ],
  [
    -91.647785890825148,
    42.154464856074
  ],
  [
    -91.647785873305082,
    42.154464810781725
  ],
  [
    -91.6477858536068,
    42.154464766393438
  ],
  [
    -91.647785831776773,
    42.15446472301381
  ],
  [
    -91.64778580786647,
    42.15446468074515
  ],
  [
    -91.647785781932285,
    42.154464639687134
  ],
  [
    -91.647785754035368,
    42.1544645999366
  ],
  [
    -91.64778572424153,
    42.1544645615873
  ],
  [
    -91.647785692621014,
    42.154464524729654
  ],
  [
    -91.647785659248413,
    42.1544644894506
  ],
  [
    -91.647785624202413,
    42.154464455833335
  ],
  [
    -91.647785587565679,
    42.154464423957137
  ],
  [
    -91.6477855494246,
    42.154464393897186
  ],
  [
    -91.647785509869138,
    42.154464365724372
  ],
  [
    -91.647785468992566,
    42.154464339505132
  ],
  [
    -91.647785426891289,
    42.154464315301304
  ],
  [
    -91.647785383664612,
    42.154464293169966
  ],
  [
    -91.647785339414455,
    42.15446427316332
  ],
  [
    -91.647785294245182,
    42.154464255328534
  ],
  [
    -91.647785248263318,
    42.154464239707679
  ],
  [
    -91.647785201577321,
    42.154464226337595
  ],
  [
    -91.647785154297267,
    42.1544642152498
  ],
  [
    -91.64778510653467,
    42.154464206470465
  ],
  [
    -91.647785058402164,
    42.154464200020278
  ],
  [
    -91.64778501001328,
    42.154464195914457
  ],
  [
    -91.647784961482117,
    42.154464194162678
  ],
  [
    -91.647593029891311,
    42.154461929937376
  ],
  [
    -91.647049659805816,
    42.154455519776377
  ],
  [
    -91.646555580964716,
    42.154449691106578
  ],
  [
    -91.646364925202917,
    42.154447441932078
  ],
  [
    -91.645742818849811,
    42.154440102915977
  ],
  [
    -91.645674498104114,
    42.154439296933077
  ],
  [
    -91.645674449323067,
    42.154439297547675
  ],
  [
    -91.645674400630057,
    42.154439300540609
  ],
  [
    -91.645674352140944,
    42.154439305904759
  ],
  [
    -91.645674303971148,
    42.154439313627357
  ],
  [
    -91.64567425623531,
    42.154439323690028
  ],
  [
    -91.64567420904703,
    42.154439336068826
  ],
  [
    -91.645674162518631,
    42.154439350734279
  ],
  [
    -91.64567411676083,
    42.154439367651484
  ],
  [
    -91.645674071882539,
    42.15443938678019
  ],
  [
    -91.64567402799058,
    42.154439408074865
  ],
  [
    -91.64567398518939,
    42.154439431484832
  ],
  [
    -91.645673943580846,
    42.154439456954364
  ],
  [
    -91.645673903263983,
    42.154439484422859
  ],
  [
    -91.645673864334739,
    42.154439513824933
  ],
  [
    -91.645673826885783,
    42.154439545090618
  ],
  [
    -91.645673791006217,
    42.154439578145492
  ],
  [
    -91.645673756781449,
    42.1544396129109
  ],
  [
    -91.645673724292934,
    42.154439649304088
  ],
  [
    -91.645673693618,
    42.154439687238444
  ],
  [
    -91.645673664829616,
    42.154439726623693
  ],
  [
    -91.645673637996339,
    42.154439767366092
  ],
  [
    -91.645673613182012,
    42.154439809368675
  ],
  [
    -91.64567359044571,
    42.154439852531489
  ],
  [
    -91.64567356984152,
    42.154439896751789
  ],
  [
    -91.6456735514185,
    42.154439941924352
  ],
  [
    -91.645673535220467,
    42.15443998794165
  ],
  [
    -91.645673521286014,
    42.154440034694176
  ],
  [
    -91.645673509648262,
    42.154440082070657
  ],
  [
    -91.645673500334937,
    42.154440129958331
  ],
  [
    -91.6456734933682,
    42.154440178243242
  ],
  [
    -91.645673488764629,
    42.154440226810465
  ],
  [
    -91.645673486535173,
    42.15444027554441
  ],
  [
    -91.645673418757141,
    42.154443454039694
  ],
  [
    -91.645420339935853,
    42.154440464297473
  ],
  [
    -91.644972195220163,
    42.154435170147373
  ],
  [
    -91.644603393775952,
    42.154430813317269
  ],
  [
    -91.644040158911963,
    42.154424159551567
  ],
  [
    -91.644015750951525,
    42.154423871208515
  ],
  [
    -91.644025600635658,
    42.154294077100218
  ],
  [
    -91.644037593138549,
    42.154136046022018
  ],
  [
    -91.644037593138549,
    42.154136046022018
  ],
  [
    -91.644037927501941,
    42.154131639963516
  ],
  [
    -91.644037927501955,
    42.154131639963317
  ],
  [
    -91.644037927501955,
    42.154131639963317
  ],
  [
    -91.644061370145153,
    42.153822724781222
  ],
  [
    -91.644061370145167,
    42.153822724781065
  ],
  [
    -91.644061370145167,
    42.153822724781065
  ],
  [
    -91.644061631467679,
    42.153819281199262
  ],
  [
    -91.644061631469114,
    42.153819281180326
  ],
  [
    -91.6440767593815,
    42.153619882670426
  ],
  [
    -91.64407675938152,
    42.153619882670277
  ],
  [
    -91.64407675938152,
    42.153619882670277
  ],
  [
    -91.644079768295015,
    42.153580222603736
  ],
  [
    -91.644933676984778,
    42.153585217740989
  ],
  [
    -91.645467173834476,
    42.15358833855479
  ],
  [
    -91.64571415052157,
    42.153589783302287
  ],
  [
    -91.645825991950872,
    42.153590437544686
  ],
  [
    -91.646105769506377,
    42.153592074168486
  ],
  [
    -91.646385098506727,
    42.153593708168188
  ],
  [
    -91.646385098506727,
    42.153593708168188
  ],
  [
    -91.646386245746427,
    42.153593714879285
  ],
  [
    -91.64638624574647,
    42.153593714879285
  ],
  [
    -91.64638624574647,
    42.153593714879285
  ],
  [
    -91.646461627847074,
    42.153594155844388
  ],
  [
    -91.647427663808074,
    42.153599806896189
  ],
  [
    -91.647461805866271,
    42.153600006618085
  ],
  [
    -91.647784620793274,
    42.153601894998886
  ],
  [
    -91.647784669880181,
    42.153601894080829
  ],
  [
    -91.647784718862866,
    42.153601890754651
  ],
  [
    -91.647784767623264,
    42.153601885028387
  ],
  [
    -91.647784816043853,
    42.153601876915822
  ],
  [
    -91.647784864007917,
    42.153601866436524
  ],
  [
    -91.647784911399839,
    42.15360185361574
  ],
  [
    -91.6477849581054,
    42.153601838484384
  ],
  [
    -91.647785004012007,
    42.153601821078922
  ],
  [
    -91.64778504900903,
    42.153601801441305
  ],
  [
    -91.647785092987974,
    42.153601779618874
  ],
  [
    -91.647785135842867,
    42.153601755664226
  ],
  [
    -91.647785177470411,
    42.1536017296351
  ],
  [
    -91.647785217770249,
    42.153601701594233
  ],
  [
    -91.64778525664525,
    42.153601671609216
  ],
  [
    -91.647785294001707,
    42.153601639752324
  ],
  [
    -91.6477853297496,
    42.153601606100352
  ],
  [
    -91.64778536380274,
    42.153601570734395
  ],
  [
    -91.647785396079058,
    42.153601533739717
  ],
  [
    -91.647785426500747,
    42.153601495205478
  ],
  [
    -91.647785454994491,
    42.15360145522456
  ],
  [
    -91.6477854814916,
    42.153601413893334
  ],
  [
    -91.647785505928212,
    42.153601371311424
  ],
  [
    -91.647785528245421,
    42.15360132758147
  ],
  [
    -91.647785548389436,
    42.153601282808872
  ],
  [
    -91.647785566311711,
    42.153601237101547
  ],
  [
    -91.647785581969032,
    42.153601190569674
  ],
  [
    -91.647785595323668,
    42.15360114332541
  ],
  [
    -91.647785606343433,
    42.153601095482628
  ],
  [
    -91.647785615001752,
    42.153601047156641
  ],
  [
    -91.647785621277777,
    42.153600998463951
  ],
  [
    -91.647785625156345,
    42.1536009495219
  ],
  [
    -91.647785626628149,
    42.153600900448481
  ],
  [
    -91.647795893340941,
    42.151711054113484
  ],
  [
    -91.647795893340941,
    42.151711054113385
  ],
  [
    -91.647795893340941,
    42.151711054113385
  ],
  [
    -91.647797974652548,
    42.1513279295137
  ],
  [
    -91.647797974652548,
    42.1513279295137
  ],
  [
    -91.647798283850946,
    42.1512710139317
  ],
  [
    -91.647798283850946,
    42.151271013931691
  ],
  [
    -91.647798283850946,
    42.151271013931691
  ],
  [
    -91.64779905697074,
    42.151128701974493
  ],
  [
    -91.64779905697074,
    42.151128701974478
  ],
  [
    -91.64779905697074,
    42.151128701974478
  ],
  [
    -91.64780007510295,
    42.150941288867976
  ],
  [
    -91.64780007510295,
    42.150941288867955
  ],
  [
    -91.64780007510295,
    42.150941288867955
  ],
  [
    -91.647801957673948,
    42.150594752390553
  ],
  [
    -91.647801957673948,
    42.150594752390532
  ],
  [
    -91.647801957673948,
    42.150594752390532
  ],
  [
    -91.64780217569205,
    42.150554620325586
  ],
  [
    -91.64780217569205,
    42.150554620325586
  ],
  [
    -91.647802635107652,
    42.150470053297283
  ],
  [
    -91.647802635107652,
    42.150470053297262
  ],
  [
    -91.647802635107652,
    42.150470053297262
  ],
  [
    -91.647804332274944,
    42.15015764585597
  ],
  [
    -91.647804332274944,
    42.15015764585597
  ],
  [
    -91.64780464367125,
    42.150100325385566
  ],
  [
    -91.647804641049916,
    42.150100247391194
  ],
  [
    -91.647804632354649,
    42.15010016983873
  ],
  [
    -91.647789179942748,
    42.149998398666035
  ],
  [
    -91.647789179942677,
    42.14999839866563
  ],
  [
    -91.647759457290192,
    42.149802641758278
  ],
  [
    -91.647759457290178,
    42.149802641758157
  ],
  [
    -91.647759457290178,
    42.149802641758157
  ],
  [
    -91.647750699334878,
    42.149744960874557
  ],
  [
    -91.647750686093332,
    42.149744890666376
  ],
  [
    -91.647750667872685,
    42.149744821582829
  ],
  [
    -91.647750644765949,
    42.14974475397657
  ],
  [
    -91.647750616891088,
    42.149744688192683
  ],
  [
    -91.647750584390366,
    42.149744624566971
  ],
  [
    -91.6477505474297,
    42.149744563424214
  ],
  [
    -91.647750506197752,
    42.149744505076519
  ],
  [
    -91.647750460904987,
    42.149744449821718
  ],
  [
    -91.64775041178261,
    42.149744397941859
  ],
  [
    -91.647750359081357,
    42.149744349701763
  ],
  [
    -91.647750303070254,
    42.149744305347689
  ],
  [
    -91.647750244035223,
    42.149744265106023
  ],
  [
    -91.647750182277576,
    42.14974422918219
  ],
  [
    -91.647750118112583,
    42.149744197759567
  ],
  [
    -91.647750051867774,
    42.149744170998545
  ],
  [
    -91.647749983881283,
    42.149744149035726
  ],
  [
    -91.6477200332896,
    42.149735642431239
  ],
  [
    -91.6477200332896,
    42.149735642431239
  ],
  [
    -91.647701306900714,
    42.14973032373824
  ],
  [
    -91.647701306900672,
    42.149730323738225
  ],
  [
    -91.647613083825576,
    42.149705266501456
  ],
  [
    -91.647613083825547,
    42.149705266501449
  ],
  [
    -91.647613083825547,
    42.149705266501442
  ],
  [
    -91.647581923994053,
    42.149696416445046
  ],
  [
    -91.647581858642909,
    42.149696400240266
  ],
  [
    -91.647581792349456,
    42.149696388469835
  ],
  [
    -91.6475817254142,
    42.149696381187105
  ],
  [
    -91.6475816581406,
    42.1496963784251
  ],
  [
    -91.6474956984858,
    42.149695745599495
  ],
  [
    -91.646507844525985,
    42.1496884731261
  ],
  [
    -91.646273937529585,
    42.149686751128094
  ],
  [
    -91.6456793806899,
    42.1496823740655
  ],
  [
    -91.64496950853939,
    42.149677148063695
  ],
  [
    -91.6448647512391,
    42.149676376851794
  ],
  [
    -91.644846897290492,
    42.149676245413
  ],
  [
    -91.6444825855356,
    42.1496735633897
  ],
  [
    -91.643917490698385,
    42.149669403222994
  ],
  [
    -91.6435941488938,
    42.1496670228157
  ],
  [
    -91.643011831245289,
    42.1496627358562
  ],
  [
    -91.6424117810404,
    42.149658318352394
  ],
  [
    -91.6398898894594,
    42.14963975246
  ],
  [
    -91.639889883179748,
    42.149639752433487
  ],
  [
    -91.639367272780646,
    42.149639186942586
  ],
  [
    -91.638654119488663,
    42.149638415274786
  ],
  [
    -91.638654119488663,
    42.149638415274786
  ],
  [
    -91.638454440205564,
    42.149638199211687
  ],
  [
    -91.63845444020555,
    42.149638199211687
  ],
  [
    -91.63845444020555,
    42.149638199211687
  ],
  [
    -91.638232603671142,
    42.149637959173383
  ]
]]],"type":"MultiPolygon","crs":null,"bbox":null},"properties":{"fieldID":10206,"zoneID":null,"color":{"r":255,"g":234,"b":134},"description":"","name":"Lyle Zumbach > Sun Valley > somefield"},"type":"Feature","crs":null,"bbox":null}

**Comment by andreacremaschi** [comment] 2015-06-23 15:37
Hi,

thank you for the reply, I found another issue in the code that creates the MKShape (`pod install` again to fix).

I can confirm that the GEOJSON you posted is being parsed correctly.
There is a syntax error in the way you handle optionals in the snippet you pasted above (compare with mine, you weren't unwrapping the optional). As the geometry is a `MultiPolygon` the returned shape will not be a simple `MKPolygon` but a `MKShapesCollection`. This is a custom MKShape subclass defined in GEOSwift, that represent a mapkit shape for GeometryCollection (this could be better described in the README).

```Swift
if let fieldgeom = Geometry.fromGeoJSON(url!),
                    let fieldgeom = fieldgeom[0] as? MultiPolygon
                    let shape = fieldgeom?.mapShape() as? MKShapesCollection {
                    mapView.addOverlay(shape)
                }
```

> Do I need a custom overlay and overlay renderer?

Yes, as you would normally implement them in `MKMapViewDelegate`.
Please let me know if you make any progress with this!

**Comment by lzumbach** [comment] 2015-06-23 16:59
I'm sorry I'm not getting a MKShapesCollection.  Maybe if the MultiPolygon is just a single polygon it is just trying to give a MKShape.  I guess I am looking to get back a collection of MKPolygons, which in the case of the example I gave just has one....Or maybe I just need a break.  Thanks for your help!

**Comment by andreacremaschi** [comment] 2015-06-24 07:36
Ugh. Two errors in my snippet of code (one missing comma, one extra question mark). Here it is the correct version:

```swift
if let fieldgeom = Geometry.fromGeoJSON(url!),
                    let fieldgeom = fieldgeom[0] as? MultiPolygon,
                    let shape = fieldgeom.mapShape() as? MKShapesCollection {
                    mapView.addOverlay(shape)
                }
```

Please be sure to execute again `pod install` since I committed some relevant changes yesterday.

**Closed** 2015-06-24 12:39 UTC
