### ISSUE TITLE
Pod geos 3.4.2a causes iTunes Connect rejection

### ISSUE THREAD

**Issue by vfn** [andreacremaschi/GEOSwift#13] opened 2015-11-18 06:08 UTC
Is it possible to update the podspec for lib GEOS, to a version that doesn't contain a letter. The current version `3.4.2a` generates the following error when submitting to iTunes Connect:

```
ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '3.4.2a' in the Info.plist file must be a period-separated list of at most three non-negative integers.
```

**Comment by andreacremaschi** [comment] 2015-11-18 08:51
Closing as it is a duplicate of https://github.com/andreacremaschi/GEOSwift/issues/10

**Closed by andreacremaschi** 2015-11-18 08:51 UTC
